version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  wex-coding-challenge:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db